### ISSUE TITLE
Need more exemple

### ISSUE THREAD

**Issue by ikarishinji98** [ngrok/ngrok-rust#102]
Hello,

Sorry, but have you an example to work with Rocket framework ?
It's built over hyper with http2 but all my test don't work...
Thx

**Comment by jrobsonchase** [comment]
Hi!

Unfortunately, rocket is unsupportable by the `ngrok` crate, at least in a direct capacity. The issue is that Rocket only offers the ability to configure the port that it listens on via its [Config](https://docs.rs/rocket/latest/rocket/config/struct.Config.html) struct, with no way to provide a generic "listener-like" object, as with the hyper server, and, by extension, tower and axum.

To work around this, you can use either the `forward_http` or `forward_tcp` methods from the [TunnelExt](https://docs.rs/ngrok/latest/ngrok/prelude/trait.TunnelExt.html) trait to automatically forward all incoming connections on a tunnel to another address, similar to how the standalone agent operates.
