### ISSUE TITLE
[Question] What is the use of ProxyProto option when using ngrok as a library via this crate?

### ISSUE THREAD

**Issue by CBenoit** [ngrok/ngrok-rust#117]
Hi!

As per the ngrok documentation:

> Add a [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) header on connection to your upstream service. This sends connection information like the original client IP address to your upstream service.

But when using this library, we have access to the original client IP address using [Conn::remote_addr](https://docs.rs/ngrok/0.13.1/ngrok/tunnel/struct.Conn.html#method.remote_addr) from _inside_ the "upstream service".

Hence my question: what’s the difference when this option is set, and how is it useful?

Thank you!

**Comment by bobzilladev** [comment]
The built-in proxy protocol support is helpful if the connection is being forwarded on to systems that already understand it. For instance if the application is going to relay the connection on to a proxy such as `nginx` or `haproxy`, that system would maintain the original client IP as it connects to the next system down the line. This can be more complicated when TLS is involved, depending on where it is being terminated, so it's convenient to have it just work by enabled the option.

It might not be applicable for an application where data is not leaving the rust process, unless a library being used could make use of the proxy header.

**Comment by CBenoit** [comment]
From your answer, I understand that the bytes I will get using the [`AsyncRead` implementation for `Conn`](https://docs.rs/ngrok/0.13.1/ngrok/struct.Conn.html#impl-AsyncRead-for-Conn) will also contain the proxy header as defined by the PROXY protocol, as-is; i.e.: it is not stripped by `ngrok-rs`, and if I were to enable this in my Rust application, I would need to parse this header before proceeding with the actual application payload. Am I correct? I think I now understand better how this could be useful depending on the use-case, thank you!

I have to admit this wasn’t immediately obvious to me what would happen just by reading the doc, and I couldn’t test it either since I only have access to a "PRO" and not an "ENTERPRISE" ngrok plan, and this feature seems to be behind the latter only as of today.

Also saw this:
https://twitter.com/russellsavage/status/1715069177797701703

Thank you all for the prompt answer!

**Comment by bobzilladev** [comment]
Thanks for your feedback! Yes, the header will appear in the payload bytes if the option is enabled. We will update the docs with more details around this feature. 

I should also note that the upcoming `0.14` release will contain updates to handling proxy protocol while doing TLS re-encrypting before forwarding a connection, that can be seen in the `0.14.0-pre.8` preview version that is currently in the `main` branch. In that case it is [parsing the proxy header off the payload bytes](https://github.com/ngrok/ngrok-rust/blob/main/ngrok/src/proxy_proto.rs#L57) in order to put it on a new outbound connection to forward traffic to.
